### PR TITLE
Built the Articles Model

### PR DESCRIPTION
**Pull request by dhirata**
Leaving a comment

### CODE REVIEW

**Comment by renzobautista** [comment]
I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project.

**Comment by dhirata** [comment]
Added the VC. Be proud.

**Comment by dhirata** [comment]
Comment

**Comment by renzobautista** [comment]
holy cow this is amazing!!!!!

**Pull request merged**
